# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c2f6698348261df9c24b7f8615f7359dda805818d96e90efb48f65d3bbbf2ec3ca37c09a73c6ab980e029e454362daf658a030dfab26602d2ffcc82ae5b50f1

test:
  secret_key_base: fe1e76ce7ad98311839299c2460ee32c32e201a404faa489000357bd561222eddd266c9045933dafde7bf24d8736d1557b47341ff409774f495602907ba89cbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
